<!doctype html>
<html>
<title>Yeti Basic Test</title>
<script type="text/javascript" src="../scripts/yui-test.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
<script>
  YUI().use("test", function (Y) {
    var SimpleTestCase = new Y.Test.Case({
      name: "Yeti Simple Test Case",
      'I should not be called as setup failed': function () {
        Y.Assert.areEqual(1, 2);
      },
      setUp: function () {
//setup is called and the exception is thrown but the test case still runs as normal
        console.log('in setup');
        throw 'err';
        console.log('leaving setup (should not hit)');
      }
    });

    var SimpleSuite = new Y.Test.Suite("Yeti Simple Test Suite");

    SimpleSuite.add(SimpleTestCase);

    Y.Test.Runner.add(SimpleSuite);

    Y.Test.Runner.run();
  });
</script>
<body>
  <div id="div1">
    <span>s1</span>
    <span>s2</span>
  </div>  
</body>
</html>
